name: Release github pages

on:
  push:
    branches:
      - release/*  # Set a branch to deploy
      #- master  # Set a branch to deploy
      #- feature/*  # Set a branch to deploy
      - deploy-aliyun-oss

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive  # Fetch the Docsy theme
        fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.83.1'
        extended: true

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install

    - name: Build public site
      run: |
        EXIT_AFTER_BUILD=1 ./scripts/build.sh
        ls -alh ./public

    - name: Publish site
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public
        external_repository: yunionio/yunionio.github.io
        allow_empty_commit: true
        cname: www.cloudpods.org
        publish_branch: master

    - name: Publish site to aliyun OSS
      uses: fangbinwei/aliyun-oss-website-action@v1.2.2
      with:
        # aliyun config
        accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
        accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
        bucket: ${{ secrets.BUCKET }}
        # deploy config
        endpoint: https://oss-cn-hongkong.aliyuncs.com
        folder: public

    # - name: Publish site to aliyun OSS
      # uses: zexi/deploy-aliyun-oss@main
      # with:
        # # aliyun config
        # region: oss-cn-hongkong.aliyuncs.com
        # access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        # access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
        # bucket: ${{ secrets.BUCKET }}
        # secure: true
        # # deploy config
        # entry: public/**/*
        # remote-dir: /
        # path-rewrite: ^public/
